#!/usr/bin/env bash

# Write following hook to ~/.zshrc to save raw cmdline
#
# # Save raw cmdline for tmux-resurrect
# if [[ -n "$TMUX_PLUGIN_MANAGER_PATH" ]]; then
#   source $TMUX_PLUGIN_MANAGER_PATH/tmux-resurrect/scripts/helpers.sh
#   mkdir -p "$(resurrect_dir)"
#   touch $(resurrect_dir)/tmux_resurrect_cmdline
#
#   # Clear cmdline which was generated by old process id when reuse it
#   sed -i "/^$$:/d" $(resurrect_dir)/tmux_resurrect_cmdline
#
#   function save_raw_cmdline_for_tmux_resurrect() {
#     sed -i "/^$$:/d" $(resurrect_dir)/tmux_resurrect_cmdline
#     echo "$$:$1" >> $(resurrect_dir)/tmux_resurrect_cmdline
#   }
#   autoload -Uz add-zsh-hook
#   add-zsh-hook preexec save_raw_cmdline_for_tmux_resurrect
# fi

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $CURRENT_DIR/../scripts/helpers.sh

PANE_PID="$1"
COMMAND_PID=$(pgrep -P $PANE_PID)

exit_safely_if_empty_ppid() {
  if [ -z "$PANE_PID" ]; then
    exit 0
  fi
}

find_raw_command() {
  [[ -z "$COMMAND_PID" ]] && exit 0

  if ! grep -q "^$PANE_PID:" $(resurrect_dir)/tmux_resurrect_cmdline; then
    exit 0
  fi

  grep "^$PANE_PID:" $(resurrect_dir)/tmux_resurrect_cmdline | sed "s/^$PANE_PID://"
}

main() {
  exit_safely_if_empty_ppid
  find_raw_command
}
main
